name: Test

on: pull_request

jobs:
  code:
    name: Test code
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: devcalendar_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: docker
        ports:
          - 5432:5432

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Setup env
        run: cp .env.example .env

      - name: Run Jest
        run: yarn test

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
